# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loader_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1068, 759)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../.designer/backup/service.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("QtDialog{\n"
"    background-color:rgb(196, 209, 212);\n"
"}\n"
"")
        Dialog.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.groupBoxMain = QtWidgets.QGroupBox(Dialog)
        self.groupBoxMain.setGeometry(QtCore.QRect(30, 20, 811, 141))
        self.groupBoxMain.setAccessibleName("")
        self.groupBoxMain.setAccessibleDescription("")
        self.groupBoxMain.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBoxMain.setStyleSheet("QGroupBox { \n"
"     border: 2px solid gray; \n"
"     border-radius: 5px; \n"
" } ")
        self.groupBoxMain.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.groupBoxMain.setObjectName("groupBoxMain")
        self.labelCurrVersionMp = QtWidgets.QLabel(self.groupBoxMain)
        self.labelCurrVersionMp.setGeometry(QtCore.QRect(40, 40, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelCurrVersionMp.setFont(font)
        self.labelCurrVersionMp.setScaledContents(True)
        self.labelCurrVersionMp.setObjectName("labelCurrVersionMp")
        self.varCurrVersionNbrMp = QtWidgets.QLabel(self.groupBoxMain)
        self.varCurrVersionNbrMp.setGeometry(QtCore.QRect(200, 40, 81, 20))
        self.varCurrVersionNbrMp.setScaledContents(True)
        self.varCurrVersionNbrMp.setObjectName("varCurrVersionNbrMp")
        self.varJLinkStateMp = QtWidgets.QLabel(self.groupBoxMain)
        self.varJLinkStateMp.setGeometry(QtCore.QRect(590, 40, 81, 20))
        self.varJLinkStateMp.setScaledContents(True)
        self.varJLinkStateMp.setObjectName("varJLinkStateMp")
        self.labelJLinkStateMp = QtWidgets.QLabel(self.groupBoxMain)
        self.labelJLinkStateMp.setGeometry(QtCore.QRect(360, 40, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelJLinkStateMp.setFont(font)
        self.labelJLinkStateMp.setScaledContents(True)
        self.labelJLinkStateMp.setObjectName("labelJLinkStateMp")
        self.varAvailableVersionNbrMp = QtWidgets.QLabel(self.groupBoxMain)
        self.varAvailableVersionNbrMp.setGeometry(QtCore.QRect(520, 90, 81, 20))
        self.varAvailableVersionNbrMp.setScaledContents(True)
        self.varAvailableVersionNbrMp.setObjectName("varAvailableVersionNbrMp")
        self.labelAvailableVersionMp = QtWidgets.QLabel(self.groupBoxMain)
        self.labelAvailableVersionMp.setGeometry(QtCore.QRect(360, 90, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelAvailableVersionMp.setFont(font)
        self.labelAvailableVersionMp.setScaledContents(True)
        self.labelAvailableVersionMp.setObjectName("labelAvailableVersionMp")
        self.varCurrVersionNbrMp_2 = QtWidgets.QLabel(self.groupBoxMain)
        self.varCurrVersionNbrMp_2.setGeometry(QtCore.QRect(200, 90, 81, 20))
        self.varCurrVersionNbrMp_2.setScaledContents(True)
        self.varCurrVersionNbrMp_2.setObjectName("varCurrVersionNbrMp_2")
        self.labelCurrIdM = QtWidgets.QLabel(self.groupBoxMain)
        self.labelCurrIdM.setGeometry(QtCore.QRect(40, 90, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelCurrIdM.setFont(font)
        self.labelCurrIdM.setScaledContents(True)
        self.labelCurrIdM.setObjectName("labelCurrIdM")
        self.pushButtonManualSet = QtWidgets.QPushButton(Dialog)
        self.pushButtonManualSet.setGeometry(QtCore.QRect(860, 20, 171, 301))
        self.pushButtonManualSet.setStyleSheet("QPushButton{\n"
"    color:rgb(85, 0, 127);\n"
"    background-color:rgb(255, 241, 167);\n"
"    border: 2px solid gray; \n"
"    border-radius: 5px; \n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(85, 255, 127);\n"
"    color:black;\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"    color:black;\n"
"    background-color:rgb(85, 255, 127);\n"
"    font: 75 14pt \"MS Shell Dlg 2\";\n"
"}")
        self.pushButtonManualSet.setObjectName("pushButtonManualSet")
        self.pushButtonUpdateId = QtWidgets.QPushButton(Dialog)
        self.pushButtonUpdateId.setGeometry(QtCore.QRect(860, 340, 171, 301))
        self.pushButtonUpdateId.setStyleSheet("QPushButton{\n"
"    color:rgb(85, 0, 127);\n"
"    background-color:rgb(255, 241, 167);\n"
"    border: 2px solid gray; \n"
"    border-radius: 5px; \n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(85, 255, 127);\n"
"    color:black;\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"    color:black;\n"
"    background-color:rgb(85, 255, 127);\n"
"    font: 75 14pt \"MS Shell Dlg 2\";\n"
"}")
        self.pushButtonUpdateId.setObjectName("pushButtonUpdateId")
        self.lineNewId = QtWidgets.QLineEdit(Dialog)
        self.lineNewId.setGeometry(QtCore.QRect(190, 670, 91, 31))
        self.lineNewId.setStyleSheet("color:rgb(85, 0, 127);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"background-color:white;")
        self.lineNewId.setAlignment(QtCore.Qt.AlignCenter)
        self.lineNewId.setObjectName("lineNewId")
        self.groupBoxNetwork = QtWidgets.QGroupBox(Dialog)
        self.groupBoxNetwork.setGeometry(QtCore.QRect(30, 180, 811, 141))
        self.groupBoxNetwork.setAccessibleName("")
        self.groupBoxNetwork.setAccessibleDescription("")
        self.groupBoxNetwork.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBoxNetwork.setStyleSheet("QGroupBox { \n"
"     border: 2px solid gray; \n"
"     border-radius: 5px; \n"
" } ")
        self.groupBoxNetwork.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.groupBoxNetwork.setObjectName("groupBoxNetwork")
        self.labelCurrVersionNw = QtWidgets.QLabel(self.groupBoxNetwork)
        self.labelCurrVersionNw.setGeometry(QtCore.QRect(40, 40, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelCurrVersionNw.setFont(font)
        self.labelCurrVersionNw.setScaledContents(True)
        self.labelCurrVersionNw.setObjectName("labelCurrVersionNw")
        self.varCurrVersionNbrNw = QtWidgets.QLabel(self.groupBoxNetwork)
        self.varCurrVersionNbrNw.setGeometry(QtCore.QRect(200, 40, 81, 20))
        self.varCurrVersionNbrNw.setScaledContents(True)
        self.varCurrVersionNbrNw.setObjectName("varCurrVersionNbrNw")
        self.varJLinkStateNw = QtWidgets.QLabel(self.groupBoxNetwork)
        self.varJLinkStateNw.setGeometry(QtCore.QRect(590, 40, 81, 20))
        self.varJLinkStateNw.setScaledContents(True)
        self.varJLinkStateNw.setObjectName("varJLinkStateNw")
        self.labelJLinkStateNw = QtWidgets.QLabel(self.groupBoxNetwork)
        self.labelJLinkStateNw.setGeometry(QtCore.QRect(360, 40, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelJLinkStateNw.setFont(font)
        self.labelJLinkStateNw.setScaledContents(True)
        self.labelJLinkStateNw.setObjectName("labelJLinkStateNw")
        self.varAvailableVersionNbrNw = QtWidgets.QLabel(self.groupBoxNetwork)
        self.varAvailableVersionNbrNw.setGeometry(QtCore.QRect(200, 90, 81, 20))
        self.varAvailableVersionNbrNw.setScaledContents(True)
        self.varAvailableVersionNbrNw.setObjectName("varAvailableVersionNbrNw")
        self.labelAvailableVersionNw = QtWidgets.QLabel(self.groupBoxNetwork)
        self.labelAvailableVersionNw.setGeometry(QtCore.QRect(40, 90, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelAvailableVersionNw.setFont(font)
        self.labelAvailableVersionNw.setScaledContents(True)
        self.labelAvailableVersionNw.setObjectName("labelAvailableVersionNw")
        self.groupBoxGuidewire = QtWidgets.QGroupBox(Dialog)
        self.groupBoxGuidewire.setGeometry(QtCore.QRect(30, 340, 811, 141))
        self.groupBoxGuidewire.setAccessibleName("")
        self.groupBoxGuidewire.setAccessibleDescription("")
        self.groupBoxGuidewire.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBoxGuidewire.setStyleSheet("QGroupBox { \n"
"     border: 2px solid gray; \n"
"     border-radius: 5px; \n"
" } ")
        self.groupBoxGuidewire.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.groupBoxGuidewire.setObjectName("groupBoxGuidewire")
        self.labelCurrVersionGw = QtWidgets.QLabel(self.groupBoxGuidewire)
        self.labelCurrVersionGw.setGeometry(QtCore.QRect(40, 40, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelCurrVersionGw.setFont(font)
        self.labelCurrVersionGw.setScaledContents(True)
        self.labelCurrVersionGw.setObjectName("labelCurrVersionGw")
        self.varCurrVersionNbrGw = QtWidgets.QLabel(self.groupBoxGuidewire)
        self.varCurrVersionNbrGw.setGeometry(QtCore.QRect(200, 40, 81, 20))
        self.varCurrVersionNbrGw.setScaledContents(True)
        self.varCurrVersionNbrGw.setObjectName("varCurrVersionNbrGw")
        self.varJLinkStateGw = QtWidgets.QLabel(self.groupBoxGuidewire)
        self.varJLinkStateGw.setGeometry(QtCore.QRect(590, 40, 81, 20))
        self.varJLinkStateGw.setScaledContents(True)
        self.varJLinkStateGw.setObjectName("varJLinkStateGw")
        self.labelJLinkStateGw = QtWidgets.QLabel(self.groupBoxGuidewire)
        self.labelJLinkStateGw.setGeometry(QtCore.QRect(360, 40, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelJLinkStateGw.setFont(font)
        self.labelJLinkStateGw.setScaledContents(True)
        self.labelJLinkStateGw.setObjectName("labelJLinkStateGw")
        self.varAvailableVersionNbrGw = QtWidgets.QLabel(self.groupBoxGuidewire)
        self.varAvailableVersionNbrGw.setGeometry(QtCore.QRect(200, 90, 81, 20))
        self.varAvailableVersionNbrGw.setScaledContents(True)
        self.varAvailableVersionNbrGw.setObjectName("varAvailableVersionNbrGw")
        self.labelAvailableVersionGw = QtWidgets.QLabel(self.groupBoxGuidewire)
        self.labelAvailableVersionGw.setGeometry(QtCore.QRect(40, 90, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelAvailableVersionGw.setFont(font)
        self.labelAvailableVersionGw.setScaledContents(True)
        self.labelAvailableVersionGw.setObjectName("labelAvailableVersionGw")
        self.groupBoxRemote = QtWidgets.QGroupBox(Dialog)
        self.groupBoxRemote.setGeometry(QtCore.QRect(30, 500, 811, 141))
        self.groupBoxRemote.setAccessibleName("")
        self.groupBoxRemote.setAccessibleDescription("")
        self.groupBoxRemote.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBoxRemote.setStyleSheet("QGroupBox { \n"
"     border: 2px solid gray; \n"
"     border-radius: 5px; \n"
" } ")
        self.groupBoxRemote.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.groupBoxRemote.setObjectName("groupBoxRemote")
        self.labelCurrVersionRem = QtWidgets.QLabel(self.groupBoxRemote)
        self.labelCurrVersionRem.setGeometry(QtCore.QRect(40, 40, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelCurrVersionRem.setFont(font)
        self.labelCurrVersionRem.setScaledContents(True)
        self.labelCurrVersionRem.setObjectName("labelCurrVersionRem")
        self.varCurrVersionNbrRem = QtWidgets.QLabel(self.groupBoxRemote)
        self.varCurrVersionNbrRem.setGeometry(QtCore.QRect(200, 40, 81, 20))
        self.varCurrVersionNbrRem.setScaledContents(True)
        self.varCurrVersionNbrRem.setObjectName("varCurrVersionNbrRem")
        self.varJLinkStateRem = QtWidgets.QLabel(self.groupBoxRemote)
        self.varJLinkStateRem.setGeometry(QtCore.QRect(590, 40, 81, 20))
        self.varJLinkStateRem.setScaledContents(True)
        self.varJLinkStateRem.setObjectName("varJLinkStateRem")
        self.labelJLinkStateRem = QtWidgets.QLabel(self.groupBoxRemote)
        self.labelJLinkStateRem.setGeometry(QtCore.QRect(360, 40, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelJLinkStateRem.setFont(font)
        self.labelJLinkStateRem.setScaledContents(True)
        self.labelJLinkStateRem.setObjectName("labelJLinkStateRem")
        self.varAvailableVersionNbrRem = QtWidgets.QLabel(self.groupBoxRemote)
        self.varAvailableVersionNbrRem.setGeometry(QtCore.QRect(200, 90, 81, 20))
        self.varAvailableVersionNbrRem.setScaledContents(True)
        self.varAvailableVersionNbrRem.setObjectName("varAvailableVersionNbrRem")
        self.labelAvailableVersionRem = QtWidgets.QLabel(self.groupBoxRemote)
        self.labelAvailableVersionRem.setGeometry(QtCore.QRect(40, 90, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelAvailableVersionRem.setFont(font)
        self.labelAvailableVersionRem.setScaledContents(True)
        self.labelAvailableVersionRem.setObjectName("labelAvailableVersionRem")
        self.labelNewId = QtWidgets.QLabel(Dialog)
        self.labelNewId.setGeometry(QtCore.QRect(50, 680, 81, 20))
        self.labelNewId.setScaledContents(True)
        self.labelNewId.setObjectName("labelNewId")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Microbot Medical Loader  Version 0.95."))
        self.groupBoxMain.setTitle(_translate("Dialog", "Main Mpu Firmware"))
        self.labelCurrVersionMp.setText(_translate("Dialog", "Current Version:"))
        self.varCurrVersionNbrMp.setText(_translate("Dialog", "xx.xx.xx"))
        self.varJLinkStateMp.setText(_translate("Dialog", "xx.xx.xx"))
        self.labelJLinkStateMp.setText(_translate("Dialog", "JLink State"))
        self.varAvailableVersionNbrMp.setText(_translate("Dialog", "xx.xx.xx"))
        self.labelAvailableVersionMp.setText(_translate("Dialog", "Available Version:"))
        self.varCurrVersionNbrMp_2.setText(_translate("Dialog", "xx.xx.xx"))
        self.labelCurrIdM.setText(_translate("Dialog", "Current Id:"))
        self.pushButtonManualSet.setText(_translate("Dialog", "Update Images"))
        self.pushButtonUpdateId.setText(_translate("Dialog", "Update Id"))
        self.lineNewId.setText(_translate("Dialog", "0"))
        self.groupBoxNetwork.setTitle(_translate("Dialog", "Network  Mpu Firmware"))
        self.labelCurrVersionNw.setText(_translate("Dialog", "Current Version:"))
        self.varCurrVersionNbrNw.setText(_translate("Dialog", "xx.xx.xx"))
        self.varJLinkStateNw.setText(_translate("Dialog", "xx.xx.xx"))
        self.labelJLinkStateNw.setText(_translate("Dialog", "JLink State"))
        self.varAvailableVersionNbrNw.setText(_translate("Dialog", "xx.xx.xx"))
        self.labelAvailableVersionNw.setText(_translate("Dialog", "Available Version:"))
        self.groupBoxGuidewire.setTitle(_translate("Dialog", "Guidewire Module Mpu Firmware"))
        self.labelCurrVersionGw.setText(_translate("Dialog", "Current Version:"))
        self.varCurrVersionNbrGw.setText(_translate("Dialog", "xx.xx.xx"))
        self.varJLinkStateGw.setText(_translate("Dialog", "xx.xx.xx"))
        self.labelJLinkStateGw.setText(_translate("Dialog", "JLink State"))
        self.varAvailableVersionNbrGw.setText(_translate("Dialog", "xx.xx.xx"))
        self.labelAvailableVersionGw.setText(_translate("Dialog", "Available Version:"))
        self.groupBoxRemote.setTitle(_translate("Dialog", "Remote Control Mpu Firmware"))
        self.labelCurrVersionRem.setText(_translate("Dialog", "Current Version:"))
        self.varCurrVersionNbrRem.setText(_translate("Dialog", "xx.xx.xx"))
        self.varJLinkStateRem.setText(_translate("Dialog", "xx.xx.xx"))
        self.labelJLinkStateRem.setText(_translate("Dialog", "JLink State"))
        self.varAvailableVersionNbrRem.setText(_translate("Dialog", "xx.xx.xx"))
        self.labelAvailableVersionRem.setText(_translate("Dialog", "Available Version:"))
        self.labelNewId.setText(_translate("Dialog", "NEW ID"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
